scrape_configs:
  - job_name: 'webapp'
    static_configs:
      - targets:
          - 'webapp:8080'

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'  # Исправлено: используйте порт 9121 для redis-exporter

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
