name: Prometheus Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Шаг для старта контейнеров
    - name: Build and start containers for a services
      run: |
        docker compose up -d
        # Логирование статуса контейнеров после запуска
        docker-compose ps
        docker-compose logs

    # Шаг для отключения брандмауэра (для временной проверки)
    - name: Disable firewall (temporary check)
      run: |
        sudo ufw disable || echo "Firewall is not active"

    # Шаг для тестирования функциональности контейнеров
    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
        CYPRESS_PROMETHEUS_URL: http://localhost:9090
      with:
        working-directory: ./.github/tests

    # Логирование всех контейнеров после выполнения тестов
    - name: Log docker containers
      run: |
        docker ps
        docker logs $(docker ps -q)
